type: satellite
main_city:
  center: [0.52, 0.52]
  proportion: 0.7
  std_dev: 0.10
satellites:
  - center: [0.18, 0.78]
    proportion: 0.15
    std_dev: 0.05
  - center: [0.82, 0.22]
    proportion: 0.15
    std_dev: 0.05
